image: node:6.10-alpine

before_script:
  - npm install

stages:
  - pages

pages:
  stage: pages
  cache:
    paths:
    - node_modules/
  script:
  - npm run build
  artifacts:
    paths:
    - public
  only:
  - master
